In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('Train.csv')
df

ID  Gender Ever_Married  Age Graduated     Profession  \
0     462809    Male           No   22        No     Healthcare   
1     462643  Female          Yes   38       Yes       Engineer   
2     466315  Female          Yes   67       Yes       Engineer   
3     461735    Male          Yes   67       Yes         Lawyer   
4     462669  Female          Yes   40       Yes  Entertainment   
...      ...     ...          ...  ...       ...            ...   
8063  464018    Male           No   22        No            NaN   
8064  464685    Male           No   35        No      Executive   
8065  465406  Female           No   33       Yes     Healthcare   
8066  467299  Female           No   27       Yes     Healthcare   
8067  461879    Male          Yes   37       Yes      Executive   

      Work_Experience Spending_Score  Family_Size  Var_1 Segmentation  
0                 1.0            Low          4.0  Cat_4            D  
1                 NaN        Average          3.0  Cat_4            A  
2                 1.0            Low          1.0  Cat_6            B  
3                 0.0           High          2.0  Cat_6            B  
4                 NaN           High          6.0  Cat_6            A  
...               ...            ...          ...    ...          ...  
8063              0.0            Low          7.0  Cat_1            D  
8064              3.0            Low          4.0  Cat_4            D  
8065              1.0            Low          1.0  Cat_6            D  
8066              1.0            Low          4.0  Cat_6            B  
8067              0.0        Average          3.0  Cat_4            B  

[8068 rows x 11 columns]

In [3]:
df.isna().sum()

ID                   0
Gender               0
Ever_Married       140
Age                  0
Graduated           78
Profession         124
Work_Experience    829
Spending_Score       0
Family_Size        335
Var_1               76
Segmentation         0
dtype: int64

In [4]:
df['Ever_Married'].mode()

0    Yes
dtype: object

In [5]:
df['Ever_Married']=df['Ever_Married'].fillna('Yes')
df.isna().any()

ID                 False
Gender             False
Ever_Married       False
Age                False
Graduated           True
Profession          True
Work_Experience     True
Spending_Score     False
Family_Size         True
Var_1               True
Segmentation       False
dtype: bool

In [7]:
df['Graduated']=df['Graduated'].fillna('Yes')
df.isna().any()

ID                 False
Gender             False
Ever_Married       False
Age                False
Graduated          False
Profession          True
Work_Experience     True
Spending_Score     False
Family_Size         True
Var_1               True
Segmentation       False
dtype: bool

In [9]:
df['Profession'].mode()

0    Artist
dtype: object

In [10]:
df['Profession']=df['Profession'].fillna('Artist')
df.isna().any()

ID                 False
Gender             False
Ever_Married       False
Age                False
Graduated          False
Profession         False
Work_Experience     True
Spending_Score     False
Family_Size         True
Var_1               True
Segmentation       False
dtype: bool

In [11]:
df['Work_Experience'].median()

1.0

In [12]:
df['Work_Experience']=df['Work_Experience'].fillna(1.0)
df.isna().any()

ID                 False
Gender             False
Ever_Married       False
Age                False
Graduated          False
Profession         False
Work_Experience    False
Spending_Score     False
Family_Size         True
Var_1               True
Segmentation       False
dtype: bool

In [13]:
df['Family_Size'].median()

3.0

In [14]:
df['Family_Size']=df['Family_Size'].fillna(3.0)
df.isna().any()

ID                 False
Gender             False
Ever_Married       False
Age                False
Graduated          False
Profession         False
Work_Experience    False
Spending_Score     False
Family_Size        False
Var_1               True
Segmentation       False
dtype: bool

In [15]:
df['Var_1'].mode()

0    Cat_6
dtype: object

In [16]:
df['Var_1']=df['Var_1'].fillna('Cat_6')
df.isna().any()

ID                 False
Gender             False
Ever_Married       False
Age                False
Graduated          False
Profession         False
Work_Experience    False
Spending_Score     False
Family_Size        False
Var_1              False
Segmentation       False
dtype: bool

In [18]:
df1=df.copy()
df1

ID  Gender Ever_Married  Age Graduated     Profession  \
0     462809    Male           No   22        No     Healthcare   
1     462643  Female          Yes   38       Yes       Engineer   
2     466315  Female          Yes   67       Yes       Engineer   
3     461735    Male          Yes   67       Yes         Lawyer   
4     462669  Female          Yes   40       Yes  Entertainment   
...      ...     ...          ...  ...       ...            ...   
8063  464018    Male           No   22        No         Artist   
8064  464685    Male           No   35        No      Executive   
8065  465406  Female           No   33       Yes     Healthcare   
8066  467299  Female           No   27       Yes     Healthcare   
8067  461879    Male          Yes   37       Yes      Executive   

      Work_Experience Spending_Score  Family_Size  Var_1 Segmentation  
0                 1.0            Low          4.0  Cat_4            D  
1                 1.0        Average          3.0  Cat_4            A  
2                 1.0            Low          1.0  Cat_6            B  
3                 0.0           High          2.0  Cat_6            B  
4                 1.0           High          6.0  Cat_6            A  
...               ...            ...          ...    ...          ...  
8063              0.0            Low          7.0  Cat_1            D  
8064              3.0            Low          4.0  Cat_4            D  
8065              1.0            Low          1.0  Cat_6            D  
8066              1.0            Low          4.0  Cat_6            B  
8067              0.0        Average          3.0  Cat_4            B  

[8068 rows x 11 columns]

In [19]:
df1['Segmentation'].unique()

array(['D', 'A', 'B', 'C'], dtype=object)

In [20]:
X=df1.drop(columns=['ID','Segmentation'])
X

Gender Ever_Married  Age Graduated     Profession  Work_Experience  \
0       Male           No   22        No     Healthcare              1.0   
1     Female          Yes   38       Yes       Engineer              1.0   
2     Female          Yes   67       Yes       Engineer              1.0   
3       Male          Yes   67       Yes         Lawyer              0.0   
4     Female          Yes   40       Yes  Entertainment              1.0   
...      ...          ...  ...       ...            ...              ...   
8063    Male           No   22        No         Artist              0.0   
8064    Male           No   35        No      Executive              3.0   
8065  Female           No   33       Yes     Healthcare              1.0   
8066  Female           No   27       Yes     Healthcare              1.0   
8067    Male          Yes   37       Yes      Executive              0.0   

     Spending_Score  Family_Size  Var_1  
0               Low          4.0  Cat_4  
1           Average          3.0  Cat_4  
2               Low          1.0  Cat_6  
3              High          2.0  Cat_6  
4              High          6.0  Cat_6  
...             ...          ...    ...  
8063            Low          7.0  Cat_1  
8064            Low          4.0  Cat_4  
8065            Low          1.0  Cat_6  
8066            Low          4.0  Cat_6  
8067        Average          3.0  Cat_4  

[8068 rows x 9 columns]

In [21]:
new_X=pd.get_dummies(X)
new_X

Age  Work_Experience  Family_Size  Gender_Female  Gender_Male  \
0      22              1.0          4.0              0            1   
1      38              1.0          3.0              1            0   
2      67              1.0          1.0              1            0   
3      67              0.0          2.0              0            1   
4      40              1.0          6.0              1            0   
...   ...              ...          ...            ...          ...   
8063   22              0.0          7.0              0            1   
8064   35              3.0          4.0              0            1   
8065   33              1.0          1.0              1            0   
8066   27              1.0          4.0              1            0   
8067   37              0.0          3.0              0            1   

      Ever_Married_No  Ever_Married_Yes  Graduated_No  Graduated_Yes  \
0                   1                 0             1              0   
1                   0                 1             0              1   
2                   0                 1             0              1   
3                   0                 1             0              1   
4                   0                 1             0              1   
...               ...               ...           ...            ...   
8063                1                 0             1              0   
8064                1                 0             1              0   
8065                1                 0             0              1   
8066                1                 0             0              1   
8067                0                 1             0              1   

      Profession_Artist  ...  Spending_Score_Average  Spending_Score_High  \
0                     0  ...                       0                    0   
1                     0  ...                       1                    0   
2                     0  ...                       0                    0   
3                     0  ...                       0                    1   
4                     0  ...                       0                    1   
...                 ...  ...                     ...                  ...   
8063                  1  ...                       0                    0   
8064                  0  ...                       0                    0   
8065                  0  ...                       0                    0   
8066                  0  ...                       0                    0   
8067                  0  ...                       1                    0   

      Spending_Score_Low  Var_1_Cat_1  Var_1_Cat_2  Var_1_Cat_3  Var_1_Cat_4  \
0                      1            0            0            0            1   
1                      0            0            0            0            1   
2                      1            0            0            0            0   
3                      0            0            0            0            0   
4                      0            0            0            0            0   
...                  ...          ...          ...          ...          ...   
8063                   1            1            0            0            0   
8064                   1            0            0            0            1   
8065                   1            0            0            0            0   
8066                   1            0            0            0            0   
8067                   0            0            0            0            1   

      Var_1_Cat_5  Var_1_Cat_6  Var_1_Cat_7  
0               0            0            0  
1               0            0            0  
2               0            1            0  
3               0            1            0  
4               0            1            0  
...           ...          ...          ...  
8063            0            0            0  
8064            0            0    

In [22]:
y=df1['Segmentation'].map({'A':1,'B':2,'C':3,'D':4})
y

0       4
1       1
2       2
3       2
4       1
       ..
8063    4
8064    4
8065    4
8066    2
8067    2
Name: Segmentation, Length: 8068, dtype: int64

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
s1=StandardScaler()

In [25]:
new=s1.fit_transform(new_X)

In [26]:
new=pd.DataFrame(new)
new

0         1         2         3         4         5         6   \
0    -1.284623 -0.451136  0.762698 -0.909164  0.909164  1.206653 -1.206653   
1    -0.327151 -0.451136  0.095802  1.099912 -1.099912 -0.828738  0.828738   
2     1.408268 -0.451136 -1.237990  1.099912 -1.099912 -0.828738  0.828738   
3     1.408268 -0.757410 -0.571094 -0.909164  0.909164 -0.828738  0.828738   
4    -0.207467 -0.451136  2.096491  1.099912 -1.099912 -0.828738  0.828738   
...        ...       ...       ...       ...       ...       ...       ...   
8063 -1.284623 -0.757410  2.763387 -0.909164  0.909164  1.206653 -1.206653   
8064 -0.506677  0.161413  0.762698 -0.909164  0.909164  1.206653 -1.206653   
8065 -0.626361 -0.451136 -1.237990  1.099912 -1.099912  1.206653 -1.206653   
8066 -0.985413 -0.451136  0.762698  1.099912 -1.099912  1.206653 -1.206653   
8067 -0.386993 -0.757410  0.095802 -0.909164  0.909164 -0.828738  0.828738   

           7        8         9   ...        18        19        20        21  \
0     1.29219 -1.29219 -0.697400  ... -0.569144 -0.421268  0.808676 -0.129465   
1    -0.77388  0.77388 -0.697400  ...  1.757024 -0.421268 -1.236590 -0.129465   
2    -0.77388  0.77388 -0.697400  ... -0.569144 -0.421268  0.808676 -0.129465   
3    -0.77388  0.77388 -0.697400  ... -0.569144  2.373788 -1.236590 -0.129465   
4    -0.77388  0.77388 -0.697400  ... -0.569144  2.373788 -1.236590 -0.129465   
...       ...      ...       ...  ...       ...       ...       ...       ...   
8063  1.29219 -1.29219  1.433897  ... -0.569144 -0.421268  0.808676  7.724096   
8064  1.29219 -1.29219 -0.697400  ... -0.569144 -0.421268  0.808676 -0.129465   
8065 -0.77388  0.77388 -0.697400  ... -0.569144 -0.421268  0.808676 -0.129465   
8066 -0.77388  0.77388 -0.697400  ... -0.569144 -0.421268  0.808676 -0.129465   
8067 -0.77388  0.77388 -0.697400  ...  1.757024 -0.421268 -1.236590 -0.129465   

           22        23        24        25        26        27  
0    -0.23493 -0.336811  2.531528 -0.103187 -1.389085 -0.160657  
1    -0.23493 -0.336811  2.531528 -0.103187 -1.389085 -0.160657  
2    -0.23493 -0.336811 -0.395018 -0.103187  0.719898 -0.160657  
3    -0.23493 -0.336811 -0.395018 -0.103187  0.719898 -0.160657  
4    -0.23493 -0.336811 -0.395018 -0.103187  0.719898 -0.160657  
...       ...       ...       ...       ...       ...       ...  
8063 -0.23493 -0.336811 -0.395018 -0.103187 -1.389085 -0.160657  
8064 -0.23493 -0.336811  2.531528 -0.103187 -1.389085 -0.160657  
8065 -0.23493 -0.336811 -0.395018 -0.103187  0.719898 -0.160657  
8066 -0.23493 -0.336811 -0.395018 -0.103187  0.719898 -0.160657  
8067 -0.23493 -0.336811  2.531528 -0.103187 -1.389085 -0.160657  

[8068 rows x 28 columns]

In [27]:
new.columns=new_X.columns

In [28]:
new.index=new_X.index

In [29]:
new

Age  Work_Experience  Family_Size  Gender_Female  Gender_Male  \
0    -1.284623        -0.451136     0.762698      -0.909164     0.909164   
1    -0.327151        -0.451136     0.095802       1.099912    -1.099912   
2     1.408268        -0.451136    -1.237990       1.099912    -1.099912   
3     1.408268        -0.757410    -0.571094      -0.909164     0.909164   
4    -0.207467        -0.451136     2.096491       1.099912    -1.099912   
...        ...              ...          ...            ...          ...   
8063 -1.284623        -0.757410     2.763387      -0.909164     0.909164   
8064 -0.506677         0.161413     0.762698      -0.909164     0.909164   
8065 -0.626361        -0.451136    -1.237990       1.099912    -1.099912   
8066 -0.985413        -0.451136     0.762698       1.099912    -1.099912   
8067 -0.386993        -0.757410     0.095802      -0.909164     0.909164   

      Ever_Married_No  Ever_Married_Yes  Graduated_No  Graduated_Yes  \
0            1.206653         -1.206653       1.29219       -1.29219   
1           -0.828738          0.828738      -0.77388        0.77388   
2           -0.828738          0.828738      -0.77388        0.77388   
3           -0.828738          0.828738      -0.77388        0.77388   
4           -0.828738          0.828738      -0.77388        0.77388   
...               ...               ...           ...            ...   
8063         1.206653         -1.206653       1.29219       -1.29219   
8064         1.206653         -1.206653       1.29219       -1.29219   
8065         1.206653         -1.206653      -0.77388        0.77388   
8066         1.206653         -1.206653      -0.77388        0.77388   
8067        -0.828738          0.828738      -0.77388        0.77388   

      Profession_Artist  ...  Spending_Score_Average  Spending_Score_High  \
0             -0.697400  ...               -0.569144            -0.421268   
1             -0.697400  ...                1.757024            -0.421268   
2             -0.697400  ...               -0.569144            -0.421268   
3             -0.697400  ...               -0.569144             2.373788   
4             -0.697400  ...               -0.569144             2.373788   
...                 ...  ...                     ...                  ...   
8063           1.433897  ...               -0.569144            -0.421268   
8064          -0.697400  ...               -0.569144            -0.421268   
8065          -0.697400  ...               -0.569144            -0.421268   
8066          -0.697400  ...               -0.569144            -0.421268   
8067          -0.697400  ...                1.757024            -0.421268   

      Spending_Score_Low  Var_1_Cat_1  Var_1_Cat_2  Var_1_Cat_3  Var_1_Cat_4  \
0               0.808676    -0.129465     -0.23493    -0.336811     2.531528   
1              -1.236590    -0.129465     -0.23493    -0.336811     2.531528   
2               0.808676    -0.129465     -0.23493    -0.336811    -0.395018   
3              -1.236590    -0.129465     -0.23493    -0.336811    -0.395018   
4              -1.236590    -0.129465     -0.23493    -0.336811    -0.395018   
...                  ...          ...          ...          ...          ...   
8063            0.808676     7.724096     -0.23493    -0.336811    -0.395018   
8064            0.808676    -0.129465     -0.23493    -0.336811     2.531528   
8065            0.808676    -0.129465     -0.23493    -0.336811    -0.395018   
8066            0.808676    -0.129465     -0.23493    -0.336811    -0.395018   
8067           -1.236590    -0.129465     -0.23493    -0.336811     2.531528   

      Var_1_Cat_5  Var_1_Cat_6  Var_1_Cat_7  
0       -0.103187    -1.389085    -0.160657  
1       -0.103187    -1.389085    -0.160657  
2       -0.103187     0.719898    -0.160657  
3       -0.103187     0.719898    -0.160657  
4       -0.103187     0.719898    -0.160657  
...           ...          ...          ...  
8063    -0.103187    -1.3

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train,X_test,y_train,y_test=train_test_split(new,y,test_size=0.2)

# LogisticRegression

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
lr=LogisticRegression(multi_class='ovr')

In [34]:
lr.fit(X_train,y_train)

C:\Users\sanka\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [35]:
lr.predict(X_test)

array([3, 4, 3, ..., 4, 1, 1], dtype=int64)

In [36]:
lr.score(X_test,y_test)

0.5173482032218092

# NaiveBayes

In [89]:
X_train,X_test,y_train,y_test=train_test_split(new_X,y,test_size=0.2,random_state=21)

In [90]:
from sklearn.naive_bayes import MultinomialNB

In [39]:
nb=MultinomialNB()

In [40]:
nb.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [41]:
nb.predict(X_test)

array([3, 4, 1, ..., 4, 1, 1], dtype=int64)

In [42]:
nb.score(X_test,y_test)

0.4857496902106567

In [43]:
from sklearn.naive_bayes  import GaussianNB

In [44]:
gnb=GaussianNB()

In [45]:
gnb.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [46]:
gnb.score(X_test,y_test)

0.4851301115241636

# XGBoost

In [87]:
from xgboost import XGBClassifier

In [91]:
X_train,X_test,y_train,y_test=train_test_split(new,y,test_size=0.2)

In [92]:
xgb=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.6, gamma=2,
              learning_rate=0.1, max_delta_step=0, max_depth=4,
              min_child_weight=1, missing=None, n_estimators=500, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=0.8, verbosity=1)

In [93]:
xgb.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [94]:
xgb.predict(X_test)

array([3, 1, 4, ..., 3, 4, 3], dtype=int64)

In [95]:
xgb.score(X_test,y_test)

0.5254027261462205

# SVC

In [102]:
from sklearn.svm import SVC

In [103]:
sv=SVC()

In [104]:
X_train,X_test,y_train,y_test=train_test_split(new,y,test_size=0.2,random_state=21)

In [105]:
sv.fit(X_train,y_train)

C:\Users\sanka\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [106]:
sv.predict(X_test)

array([3, 4, 1, ..., 4, 1, 2], dtype=int64)

In [107]:
sv.score(X_test,y_test)

0.5192069392812887

# RandomForest

In [136]:
from sklearn.ensemble import RandomForestClassifier

In [138]:
X_train,X_test,y_train,y_test=train_test_split(new,y,test_size=0.2,random_state=21)

In [146]:
rfc=RandomForestClassifier(n_estimators=1000)

In [147]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [148]:
rfc.predict(X_test)

array([3, 4, 2, ..., 4, 1, 2], dtype=int64)

In [149]:
rfc.score(X_test,y_test)

0.48141263940520446

# Neural Net

In [3]:
import keras

Using TensorFlow backend.


ModuleNotFoundError: No module named 'tensorflow'

# Importing test data

In [47]:
test=pd.read_csv('Test.csv')

In [48]:
test

ID  Gender Ever_Married  Age Graduated     Profession  \
0     458989  Female          Yes   36       Yes       Engineer   
1     458994    Male          Yes   37       Yes     Healthcare   
2     458996  Female          Yes   69        No            NaN   
3     459000    Male          Yes   59        No      Executive   
4     459001  Female           No   19        No      Marketing   
...      ...     ...          ...  ...       ...            ...   
2622  467954    Male           No   29        No     Healthcare   
2623  467958  Female           No   35       Yes         Doctor   
2624  467960  Female           No   53       Yes  Entertainment   
2625  467961    Male          Yes   47       Yes      Executive   
2626  467968  Female           No   43       Yes     Healthcare   

      Work_Experience Spending_Score  Family_Size  Var_1  
0                 0.0            Low          1.0  Cat_6  
1                 8.0        Average          4.0  Cat_6  
2                 0.0            Low          1.0  Cat_6  
3                11.0           High          2.0  Cat_6  
4                 NaN            Low          4.0  Cat_6  
...               ...            ...          ...    ...  
2622              9.0            Low          4.0  Cat_6  
2623              1.0            Low          1.0  Cat_6  
2624              NaN            Low          2.0  Cat_6  
2625              1.0           High          5.0  Cat_4  
2626              9.0            Low          3.0  Cat_7  

[2627 rows x 10 columns]

In [49]:
test.isna().sum()

ID                   0
Gender               0
Ever_Married        50
Age                  0
Graduated           24
Profession          38
Work_Experience    269
Spending_Score       0
Family_Size        113
Var_1               32
dtype: int64

In [50]:
test['Ever_Married']=test['Ever_Married'].fillna('Yes')

In [51]:
test.isna().any()

ID                 False
Gender             False
Ever_Married       False
Age                False
Graduated           True
Profession          True
Work_Experience     True
Spending_Score     False
Family_Size         True
Var_1               True
dtype: bool

In [52]:
test['Graduated'].mode()

0    Yes
dtype: object

In [53]:
test['Graduated']=test['Graduated'].fillna('Yes')
test['Graduated'].isna().any()

False

In [54]:
test['Profession'].mode()

0    Artist
dtype: object

In [55]:
test['Profession']=test['Profession'].fillna('Artist')
test['Profession'].isna().any()

False

In [56]:
test['Work_Experience'].median()

1.0

In [57]:
test['Work_Experience']=test['Work_Experience'].fillna(1.0)
test['Work_Experience'].isna().any()

False

In [58]:
test['Family_Size'].median()

2.0

In [59]:
test['Family_Size']=test['Family_Size'].fillna(2.0)
test['Family_Size'].isna().any()

False

In [60]:
test['Var_1'].mode()

0    Cat_6
dtype: object

In [61]:
test['Var_1']=test['Var_1'].fillna('Cat_6')
test.isna().any()

ID                 False
Gender             False
Ever_Married       False
Age                False
Graduated          False
Profession         False
Work_Experience    False
Spending_Score     False
Family_Size        False
Var_1              False
dtype: bool

In [62]:
test1=pd.get_dummies(test)
test1

ID  Age  Work_Experience  Family_Size  Gender_Female  Gender_Male  \
0     458989   36              0.0          1.0              1            0   
1     458994   37              8.0          4.0              0            1   
2     458996   69              0.0          1.0              1            0   
3     459000   59             11.0          2.0              0            1   
4     459001   19              1.0          4.0              1            0   
...      ...  ...              ...          ...            ...          ...   
2622  467954   29              9.0          4.0              0            1   
2623  467958   35              1.0          1.0              1            0   
2624  467960   53              1.0          2.0              1            0   
2625  467961   47              1.0          5.0              0            1   
2626  467968   43              9.0          3.0              1            0   

      Ever_Married_No  Ever_Married_Yes  Graduated_No  Graduated_Yes  ...  \
0                   0                 1             0              1  ...   
1                   0                 1             0              1  ...   
2                   0                 1             1              0  ...   
3                   0                 1             1              0  ...   
4                   1                 0             1              0  ...   
...               ...               ...           ...            ...  ...   
2622                1                 0             1              0  ...   
2623                1                 0             0              1  ...   
2624                1                 0             0              1  ...   
2625                0                 1             0              1  ...   
2626                1                 0             0              1  ...   

      Spending_Score_Average  Spending_Score_High  Spending_Score_Low  \
0                          0                    0                   1   
1                          1                    0                   0   
2                          0                    0                   1   
3                          0                    1                   0   
4                          0                    0                   1   
...                      ...                  ...                 ...   
2622                       0                    0                   1   
2623                       0                    0                   1   
2624                       0                    0                   1   
2625                       0                    1                   0   
2626                       0                    0                   1   

      Var_1_Cat_1  Var_1_Cat_2  Var_1_Cat_3  Var_1_Cat_4  Var_1_Cat_5  \
0               0            0            0            0            0   
1               0            0            0            0            0   
2               0            0            0            0            0   
3               0            0            0            0            0   
4               0            0            0            0            0   
...           ...          ...          ...          ...          ...   
2622            0            0            0            0            0   
2623            0            0            0            0            0   
2624            0            0            0            0            0   
2625            0            0            0            1            0   
2626            0            0            0            0            0   

      Var_1_Cat_6  Var_1_Cat_7  
0               1            0  
1               1            0  
2               1            0  
3               1            0  
4               1            0  
...           ...          ...  
2622            1            0  
2623            1            0  
2624            1            0  
2625            0            0  
2626            0  

In [63]:
test1=test1.drop(columns='ID')
test1

Age  Work_Experience  Family_Size  Gender_Female  Gender_Male  \
0      36              0.0          1.0              1            0   
1      37              8.0          4.0              0            1   
2      69              0.0          1.0              1            0   
3      59             11.0          2.0              0            1   
4      19              1.0          4.0              1            0   
...   ...              ...          ...            ...          ...   
2622   29              9.0          4.0              0            1   
2623   35              1.0          1.0              1            0   
2624   53              1.0          2.0              1            0   
2625   47              1.0          5.0              0            1   
2626   43              9.0          3.0              1            0   

      Ever_Married_No  Ever_Married_Yes  Graduated_No  Graduated_Yes  \
0                   0                 1             0              1   
1                   0                 1             0              1   
2                   0                 1             1              0   
3                   0                 1             1              0   
4                   1                 0             1              0   
...               ...               ...           ...            ...   
2622                1                 0             1              0   
2623                1                 0             0              1   
2624                1                 0             0              1   
2625                0                 1             0              1   
2626                1                 0             0              1   

      Profession_Artist  ...  Spending_Score_Average  Spending_Score_High  \
0                     0  ...                       0                    0   
1                     0  ...                       1                    0   
2                     1  ...                       0                    0   
3                     0  ...                       0                    1   
4                     0  ...                       0                    0   
...                 ...  ...                     ...                  ...   
2622                  0  ...                       0                    0   
2623                  0  ...                       0                    0   
2624                  0  ...                       0                    0   
2625                  0  ...                       0                    1   
2626                  0  ...                       0                    0   

      Spending_Score_Low  Var_1_Cat_1  Var_1_Cat_2  Var_1_Cat_3  Var_1_Cat_4  \
0                      1            0            0            0            0   
1                      0            0            0            0            0   
2                      1            0            0            0            0   
3                      0            0            0            0            0   
4                      1            0            0            0            0   
...                  ...          ...          ...          ...          ...   
2622                   1            0            0            0            0   
2623                   1            0            0            0            0   
2624                   1            0            0            0            0   
2625                   0            0            0            0            1   
2626                   1            0            0            0            0   

      Var_1_Cat_5  Var_1_Cat_6  Var_1_Cat_7  
0               0            1            0  
1               0            1            0  
2               0            1            0  
3               0            1            0  
4               0            1            0  
...           ...          ...          ...  
2622            0            1            0  
2623            0            1    

In [64]:
test1

Age  Work_Experience  Family_Size  Gender_Female  Gender_Male  \
0      36              0.0          1.0              1            0   
1      37              8.0          4.0              0            1   
2      69              0.0          1.0              1            0   
3      59             11.0          2.0              0            1   
4      19              1.0          4.0              1            0   
...   ...              ...          ...            ...          ...   
2622   29              9.0          4.0              0            1   
2623   35              1.0          1.0              1            0   
2624   53              1.0          2.0              1            0   
2625   47              1.0          5.0              0            1   
2626   43              9.0          3.0              1            0   

      Ever_Married_No  Ever_Married_Yes  Graduated_No  Graduated_Yes  \
0                   0                 1             0              1   
1                   0                 1             0              1   
2                   0                 1             1              0   
3                   0                 1             1              0   
4                   1                 0             1              0   
...               ...               ...           ...            ...   
2622                1                 0             1              0   
2623                1                 0             0              1   
2624                1                 0             0              1   
2625                0                 1             0              1   
2626                1                 0             0              1   

      Profession_Artist  ...  Spending_Score_Average  Spending_Score_High  \
0                     0  ...                       0                    0   
1                     0  ...                       1                    0   
2                     1  ...                       0                    0   
3                     0  ...                       0                    1   
4                     0  ...                       0                    0   
...                 ...  ...                     ...                  ...   
2622                  0  ...                       0                    0   
2623                  0  ...                       0                    0   
2624                  0  ...                       0                    0   
2625                  0  ...                       0                    1   
2626                  0  ...                       0                    0   

      Spending_Score_Low  Var_1_Cat_1  Var_1_Cat_2  Var_1_Cat_3  Var_1_Cat_4  \
0                      1            0            0            0            0   
1                      0            0            0            0            0   
2                      1            0            0            0            0   
3                      0            0            0            0            0   
4                      1            0            0            0            0   
...                  ...          ...          ...          ...          ...   
2622                   1            0            0            0            0   
2623                   1            0            0            0            0   
2624                   1            0            0            0            0   
2625                   0            0            0            0            1   
2626                   1            0            0            0            0   

      Var_1_Cat_5  Var_1_Cat_6  Var_1_Cat_7  
0               0            1            0  
1               0            1            0  
2               0            1            0  
3               0            1            0  
4               0            1            0  
...           ...          ...          ...  
2622            0            1            0  
2623            0            1    

In [65]:
pred=nb.predict(test1)
pred

array([2, 4, 2, ..., 1, 2, 4], dtype=int64)

In [66]:
test['Segmentation']=pred

In [67]:
test['Segmentation']=test['Segmentation'].map({1:'A',2:'B',3:'C',4:'D'})
submission=test[['ID','Segmentation']]

In [68]:
test['Segmentation']

0       B
1       D
2       B
3       A
4       D
       ..
2622    D
2623    A
2624    A
2625    B
2626    D
Name: Segmentation, Length: 2627, dtype: object

In [69]:
submission

ID Segmentation
0     458989            B
1     458994            D
2     458996            B
3     459000            A
4     459001            D
...      ...          ...
2622  467954            D
2623  467958            A
2624  467960            A
2625  467961            B
2626  467968            D

[2627 rows x 2 columns]

In [70]:
submission.to_csv('Multinomial_updated.csv',index=False)

# Gaussian

In [71]:
pred_gau=gnb.predict(test1)

In [72]:
test['Segmentation']=pred_gau

In [73]:
test['Segmentation']=test['Segmentation'].map({1:'A',2:'B',3:'C',4:'D'})
submission=test[['ID','Segmentation']]

In [74]:
submission.to_csv('Gaussian_updated.csv',index=False)

# Logistic

In [75]:
from sklearn.preprocessing import StandardScaler

In [76]:
s=StandardScaler()

In [77]:
log_x=pd.DataFrame(s.fit_transform(test1))

In [78]:
log_x.columns=test1.columns

In [79]:
log_x.index=test1.index

In [80]:
log_x

Age  Work_Experience  Family_Size  Gender_Female  Gender_Male  \
0    -0.450948        -0.748105    -1.172097       1.087983    -1.087983   
1    -0.391999         1.752242     0.792450      -0.919132     0.919132   
2     1.494372        -0.748105    -1.172097       1.087983    -1.087983   
3     0.904881         2.689872    -0.517248      -0.919132     0.919132   
4    -1.453083        -0.435562     0.792450       1.087983    -1.087983   
...        ...              ...          ...            ...          ...   
2622 -0.863592         2.064785     0.792450      -0.919132     0.919132   
2623 -0.509897        -0.435562    -1.172097       1.087983    -1.087983   
2624  0.551187        -0.435562    -0.517248       1.087983    -1.087983   
2625  0.197492        -0.435562     1.447299      -0.919132     0.919132   
2626 -0.038305         2.064785     0.137601       1.087983    -1.087983   

      Ever_Married_No  Ever_Married_Yes  Graduated_No  Graduated_Yes  \
0           -0.820517          0.820517     -0.784615       0.784615   
1           -0.820517          0.820517     -0.784615       0.784615   
2           -0.820517          0.820517      1.274510      -1.274510   
3           -0.820517          0.820517      1.274510      -1.274510   
4            1.218744         -1.218744      1.274510      -1.274510   
...               ...               ...           ...            ...   
2622         1.218744         -1.218744      1.274510      -1.274510   
2623         1.218744         -1.218744     -0.784615       0.784615   
2624         1.218744         -1.218744     -0.784615       0.784615   
2625        -0.820517          0.820517     -0.784615       0.784615   
2626         1.218744         -1.218744     -0.784615       0.784615   

      Profession_Artist  ...  Spending_Score_Average  Spending_Score_High  \
0             -0.685610  ...               -0.558738            -0.415024   
1             -0.685610  ...                1.789749            -0.415024   
2              1.458554  ...               -0.558738            -0.415024   
3             -0.685610  ...               -0.558738             2.409502   
4             -0.685610  ...               -0.558738            -0.415024   
...                 ...  ...                     ...                  ...   
2622          -0.685610  ...               -0.558738            -0.415024   
2623          -0.685610  ...               -0.558738            -0.415024   
2624          -0.685610  ...               -0.558738            -0.415024   
2625          -0.685610  ...               -0.558738             2.409502   
2626          -0.685610  ...               -0.558738            -0.415024   

      Spending_Score_Low  Var_1_Cat_1  Var_1_Cat_2  Var_1_Cat_3  Var_1_Cat_4  \
0               0.790961    -0.114509    -0.238155    -0.336356    -0.415024   
1              -1.264285    -0.114509    -0.238155    -0.336356    -0.415024   
2               0.790961    -0.114509    -0.238155    -0.336356    -0.415024   
3              -1.264285    -0.114509    -0.238155    -0.336356    -0.415024   
4               0.790961    -0.114509    -0.238155    -0.336356    -0.415024   
...                  ...          ...          ...          ...          ...   
2622            0.790961    -0.114509    -0.238155    -0.336356    -0.415024   
2623            0.790961    -0.114509    -0.238155    -0.336356    -0.415024   
2624            0.790961    -0.114509    -0.238155    -0.336356    -0.415024   
2625           -1.264285    -0.114509    -0.238155    -0.336356     2.409502   
2626            0.790961    -0.114509    -0.238155    -0.336356    -0.415024   

      Var_1_Cat_5  Var_1_Cat_6  Var_1_Cat_7  
0       -0.105652     0.735980    -0.160534  
1       -0.105652     0.735980    -0.160534  
2       -0.105652     0.735980    -0.160534  
3       -0.105652     0.735980    -0.160534  
4       -0.105652     0.735980    -0.160534  
...           ...          ...          ...  
2622    -0.105652     0.7

In [81]:
pred_log=lr.predict(log_x)

In [82]:
pred_log

array([1, 3, 2, ..., 1, 2, 4], dtype=int64)

In [83]:
test['Segmentation']=pred_log


In [84]:
test['Segmentation']=test['Segmentation'].map({1:'A',2:'B',3:'C',4:'D'})
submission=test[['ID','Segmentation']]

In [85]:
submission.to_csv('Logistic_updated.csv',index=False)

# XGBoost

In [98]:
pred_xg=xgb.predict(log_x)

In [99]:
test['Segmentation']=pred_xg


In [100]:
test['Segmentation']=test['Segmentation'].map({1:'A',2:'B',3:'C',4:'D'})
submission=test[['ID','Segmentation']]

In [101]:
submission.to_csv('Xgb_updated.csv',index=False)

# SVC

In [108]:
pred_svc=sv.predict(log_x)

In [109]:
test['Segmentation']=pred_svc


In [110]:
test['Segmentation']=test['Segmentation'].map({1:'A',2:'B',3:'C',4:'D'})
submission=test[['ID','Segmentation']]

In [111]:
submission.to_csv('svc_updated.csv',index=False)

# hfh

In [112]:
pred

array([2, 4, 2, ..., 1, 2, 4], dtype=int64)

In [113]:
pred_gau

array([1, 3, 3, ..., 1, 2, 4], dtype=int64)

In [114]:
pred_log

array([1, 3, 2, ..., 1, 2, 4], dtype=int64)

In [115]:
pred_xg

array([1, 3, 3, ..., 1, 2, 4], dtype=int64)

In [116]:
pred_svc

array([1, 3, 2, ..., 1, 2, 4], dtype=int64)

In [127]:
final=pd.DataFrame({'Multi':pred,'Gaussian':pred_gau,'Logistic':pred_log,'XGboost':pred_xg,'SVC':pred_svc})
final

Multi  Gaussian  Logistic  XGboost  SVC
0         2         1         1        1    1
1         4         3         3        3    3
2         2         3         2        3    2
3         1         2         2        3    3
4         4         4         4        4    4
...     ...       ...       ...      ...  ...
2622      4         4         4        4    4
2623      1         1         1        1    1
2624      1         1         1        1    1
2625      2         2         2        2    2
2626      4         4         4        4    4

[2627 rows x 5 columns]

In [130]:
final['Segmentation']=final.mode(axis=1)[0]
final

Multi  Gaussian  Logistic  XGboost  SVC  Segmentation
0         2         1         1        1    1           1.0
1         4         3         3        3    3           3.0
2         2         3         2        3    2           2.0
3         1         2         2        3    3           2.0
4         4         4         4        4    4           4.0
...     ...       ...       ...      ...  ...           ...
2622      4         4         4        4    4           4.0
2623      1         1         1        1    1           1.0
2624      1         1         1        1    1           1.0
2625      2         2         2        2    2           2.0
2626      4         4         4        4    4           4.0

[2627 rows x 6 columns]

In [131]:
final['ID']=test['ID']
final

Multi  Gaussian  Logistic  XGboost  SVC  Segmentation      ID
0         2         1         1        1    1           1.0  458989
1         4         3         3        3    3           3.0  458994
2         2         3         2        3    2           2.0  458996
3         1         2         2        3    3           2.0  459000
4         4         4         4        4    4           4.0  459001
...     ...       ...       ...      ...  ...           ...     ...
2622      4         4         4        4    4           4.0  467954
2623      1         1         1        1    1           1.0  467958
2624      1         1         1        1    1           1.0  467960
2625      2         2         2        2    2           2.0  467961
2626      4         4         4        4    4           4.0  467968

[2627 rows x 7 columns]

In [132]:
submission=final[['ID','Segmentation']]
submission

ID  Segmentation
0     458989           1.0
1     458994           3.0
2     458996           2.0
3     459000           2.0
4     459001           4.0
...      ...           ...
2622  467954           4.0
2623  467958           1.0
2624  467960           1.0
2625  467961           2.0
2626  467968           4.0

[2627 rows x 2 columns]

In [134]:
submission['Segmentation']=submission['Segmentation'].map({1:'A',2:'B',3:'C',4:'D'})

C:\Users\sanka\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [135]:
submission.to_csv('combined.csv',index=False)